### ISSUE TITLE
"error while getting pool information strconv.ParseUint: parsing "": invalid syntax" in docker info

### ISSUE THREAD

**Issue by Boldie** [mistifyio/go-zfs#56] opened 2017-01-30 06:47 UTC
While installing docker I had a serious problem with my ZFS-Installation. My installation had no fragmentation determination enabled and therefore the command 
```
root@atomic:~# zpool get -p name,health,allocated,size,free,readonly,dedupratio,fragmentation,freeing,leaked tank
NAME  PROPERTY       VALUE    SOURCE
tank  name           tank     -
tank  health         ONLINE   -
tank  allocated      2098558267392  -
tank  size           2989297238016  -
tank  free           890738970624  -
tank  readonly       off      -
tank  dedupratio     1.00x    -
tank  fragmentation  -        -
tank  freeing        0        default
tank  leaked         0        default
```
can not be parsed. the lib struggles with the "-" in fragmentation. This results in the following error message: "Zpool: error while getting pool information strconv.ParseUint: parsing "": invalid syntax"

Original issue in Docker issue trakcer: https://github.com/docker/docker/issues/30551

**Comment by thaJeztah** [comment] 2017-11-02 14:50
ping @Mic92 ptal

**Comment by thaJeztah** [comment] 2017-11-02 14:51
looks related to https://github.com/mistifyio/go-zfs/issues/62 ?

**Comment by Mic92** [comment] 2017-11-02 16:39
I think this was fixed upstream here: 4a9c7e5cde4c3c9dd3fd1d5cb0ac69597b56c671
Docker needs to update its go-zfs fork.

**Comment by thaJeztah** [comment] 2017-11-02 16:40
Ah, even better; I can bump the vendored package

**Comment by Mic92** [comment] 2017-11-02 16:41
I can quickly make fix.

**Comment by thaJeztah** [comment] 2017-11-02 16:46
Oh, already working on it, I'll ping you when it's up

**Comment by Mic92** [comment] 2017-11-02 16:48
@thaJeztah 

untested:

```diff
diff --git a/utils.go b/utils.go
index 3ae4236..2a27718 100644
--- a/utils.go
+++ b/utils.go
@@ -340,12 +340,15 @@ func (z *Zpool) parseLine(line []string) error {
        case "free":
                err = setUint(&z.Free, val)
        case "fragmentation":
-               // Trim trailing "%" before parsing uint
-               i := strings.Index(val, "%")
-               if i < 0 {
-                       i = len(val)
+               // if no fragmentation determination is enabled, this field is a `-`
+               if val != "-" {
+                       // Trim trailing "%" before parsing uint
+                       idx := strings.Index(val, "%")
+                       if idx < 0 {
+                               i = len(val)
+                       }
+                       err = setUint(&z.Fragmentation, val[:i])
                }
-               err = setUint(&z.Fragmentation, val[:i])
        case "readonly":
                z.ReadOnly = val == "on"
        case "freeing":
```

**Comment by thaJeztah** [comment] 2017-11-02 16:50
The code is vendored, so bumping the commit should probably do it :)

**Comment by Mic92** [comment] 2017-11-02 16:50
@thaJeztah this fix is not upstream yet.

**Comment by thaJeztah** [comment] 2017-11-02 16:55
oh!  I must've misunderstood; isn't bumping the vendored github.com/mistifyio/go-zfs package bringing in the change?

Oh! it's the `if val != "-" {` that you added; now I see :blush: yes, if you can open a PR for that, then I can bump the vendor after it's merged

**Comment by nofunatall** [comment] 2018-07-12 10:15
According to a commit on zpool.go the function for GetZpool was changed from using zpool get to zpool list.
https://github.com/mistifyio/go-zfs/commit/ae41c47571abdb8e89ff6e8d6603b8a8d62c68bd

I can't really understand how the change made to that file would possibly invoke a zpool list or return any data at all really which it appears as though that is what docker is getting from GetZpool.
Although I am not a go expert in the very least.

From zfs.go these values all return back fine except for poolName and poolHealth which are the only two that are derived from using GetZpool.
`	return [][2]string{
		{"Zpool", poolName},
		{"Zpool Health", poolHealth},
		{"Parent Dataset", d.dataset.Name},
		{"Space Used By Parent", strconv.FormatUint(d.dataset.Used, 10)},
		{"Space Available", strconv.FormatUint(d.dataset.Avail, 10)},
		{"Parent Quota", quota},
		{"Compression", d.dataset.Compression},
	}`

**Comment by spamwax** [comment] 2019-06-22 22:41
Is it safe to assume that this is only a cosmetic issue and doesn't affect the performance of `docker`?

**Comment by alphaDev23** [comment] 2020-07-03 17:18
Same question as @spamwax; the question is over a year old.  The issue is 3 years old.  This project appears to be inactive.

**Comment by Mic92** [comment] 2020-07-04 08:42
Well none of the people having this problem tested my patch, so we cannot merge it.
On my systems zfs + docker works fine.

**Comment by alphaDev23** [comment] 2020-07-04 16:15
@Mic92 Thank you for providing the patch.  I've replied on https://github.com/moby/moby/issues/30551.

**Closed** 2022-04-01 03:38 UTC
